#!/usr/bin/perl
use strict;
use warnings;

use MIDI::Simple::Drummer::Euclidean;

my $d = MIDI::Simple::Drummer::Euclidean->new(
    -file   => "$0.mid",
    -bpm    => 70,
    -onsets => 4,
    -beats  => 6,
);

$d->sync_tracks(
    sub {
        $d->{-rhythm} = [qw( x . x x x . )];
        $d->beat(-name => 1);
    },
    sub {
        $d->{-rhythm} = [qw( x . . x x . )];
        $d->beat(-name => 1);
    },
);

$d->write();
