#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple::Drummer::Rock;

my $d = MIDI::Simple::Drummer::Rock->new(
    -bpm     => shift || 100,
    -volume  => shift || 100,
    -phrases => shift || 2,
    -file    => "$0.mid",
);

my ($beat, $fill) = (0, 0);
my @rotate = qw( 2.2 2.4 2.5 );

$d->count_in;

for my $p (1 .. $d->phrases) {
    if($p % 2 > 0) {
        $beat = $d->beat(-name => 2.3, -fill => $fill);
        $beat = $d->beat(-name => 2.3);
    }
    else {
        $beat = $d->beat(-name => (@rotate)[int(rand @rotate)]);
        $fill = $d->fill(-last => $fill);
    }
}

#fin($d); # <- Perfectly reasonable but use the API:
$d->patterns('end fill' => \&fin);
$d->fill(-name => 'end');

$d->write;

sub fin {
    my $d = shift;
    $d->accent;
    $d->note('qn', $d->strike('Crash Cymbal 1', $d->name_of('kick')));
}
