#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple::Drummer;
my $d = MIDI::Simple::Drummer->new(
    -signature => shift || '4/4',
    -phrases   => shift || 1,
    -bpm       => shift || 100,
    -volume    => shift || 100,
);
warn 'Div: ',$d->{-div_name}->(),"\n";
$d->kick('Bass Drum 1');
$d->count_in; # Bar of 8th hhat
for my $i (0 .. $d->phrases) {
    $d->note($d->doubletime(), $d->backbeat_rhythm(-beat => $i));
    $d->note($d->{-div_name}->(), $d->tick);
}
$d->write("$0.mid");
